name: WakaTime Readme

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: WakaTime Readme Stats
        uses: athul/waka-readme@master # This always uses the latest version
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: true # Shows time spent on each language
          SHOW_TOTAL: true # Shows total coding time
          TIME_RANGE: last_7_days # Weekly data
          LANG_COUNT: 5 # Top 5 languages only
