name: WakaTime Readme

on:
  schedule:
    - cron: '0 0 * * *' # Runs every hour
  workflow_dispatch: # Allows manual run

jobs:
  update-readme:
    name: Update WakaTime Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: WakaTime Readme
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIME: true
          SHOW_TOTAL: true
          LANG_COUNT: 5
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          STOP_AT_OTHER: true
          TARGET_PATH: README.md
s
